### ISSUE TITLE
fails to install on mac

### ISSUE THREAD

**Issue by tommyjcarpenter** [pythongssapi/python-gssapi#169]
### What went wrong?
Tried to pip install this package on macosx-10.14 and it failed with python 3.7.2

### How do we reproduce?

Try to install this package using `pip install python-gssapi` on macosx-10.14 with python 3.7.2

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)

Tried to do `pip install python-gssapi` on macosx-10.14 after doing `pip install paramiko`

Stack:

```
pip install  python-gssapi
Collecting python-gssapi
  Downloading https://files.pythonhosted.org/packages/a4/9e/648b4e85235097edcee561c986f7075cb1606be24c514cfcdd2930e35c5e/python-gssapi-0.6.4.tar.gz
Requirement already satisfied: cffi>=0.8 in /Users/tommy/.pyenv/versions/3.7.2/envs/paramiko/lib/python3.7/site-packages (from python-gssapi) (1.12.2)
Requirement already satisfied: six>=1.5.0 in /Users/tommy/.pyenv/versions/3.7.2/envs/paramiko/lib/python3.7/site-packages (from python-gssapi) (1.12.0)
Requirement already satisfied: pyasn1>=0.1.2 in /Users/tommy/.pyenv/versions/3.7.2/envs/paramiko/lib/python3.7/site-packages (from python-gssapi) (0.4.5)
Requirement already satisfied: pycparser in /Users/tommy/.pyenv/versions/3.7.2/envs/paramiko/lib/python3.7/site-packages (from cffi>=0.8->python-gssapi) (2.19)
Building wheels for collected packages: python-gssapi
  Building wheel for python-gssapi (setup.py) ... error
  Complete output from command /Users/tommy/.pyenv/versions/3.7.2/envs/paramiko/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/7s/9r15tdh50rz2n2ndx43j2m3w0000gp/T/pip-install-3zpmrshy/python-gssapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/7s/9r15tdh50rz2n2ndx43j2m3w0000gp/T/pip-wheel-wtutny04 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  copying gssapi_ez_setup.py -> build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/gssapi
  copying gssapi/error.py -> build/lib.macosx-10.14-x86_64-3.7/gssapi
  copying gssapi/creds.py -> build/lib.macosx-10.14-x86_64-3.7/gssapi
  copying gssapi/chanbind.py -> build/lib.macosx-10.14-x86_64-3.7/gssapi
  copying gssapi/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/gssapi
  copying gssapi/names.py -> build/lib.macosx-10.14-x86_64-3.7/gssapi
  copying gssapi/oids.py -> build/lib.macosx-10.14-x86_64-3.7/gssapi
  copying gssapi/__about__.py -> build/lib.macosx-10.14-x86_64-3.7/gssapi
  copying gssapi/ctx.py -> build/lib.macosx-10.14-x86_64-3.7/gssapi
  creating build/lib.macosx-10.14-x86_64-3.7/gssapi/bindings
  copying gssapi/bindings/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/gssapi/bindings
  copying gssapi/bindings/autogenerated.cdef -> build/lib.macosx-10.14-x86_64-3.7/gssapi/bindings
  copying gssapi/bindings/cffi_gssapi.cdef -> build/lib.macosx-10.14-x86_64-3.7/gssapi/bindings
  running build_ext
  building '_cffi__xa89f429exac4dd3e8' extension
  creating build/temp.macosx-10.14-x86_64-3.7
  creating build/temp.macosx-10.14-x86_64-3.7/gssapi
  creating build/temp.macosx-10.14-x86_64-3.7/gssapi/bindings
  creating build/temp.macosx-10.14-x86_64-3.7/gssapi/bindings/__pycache__
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/tommy/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/include/python3.7m -c gssapi/bindings/__pycache__/_cffi__xa89f429exac4dd3e8.c -o build/temp.macosx-10.14-x86_64-3.7/gssapi/bindings/__pycache__/_cffi__xa89f429exac4dd3e8.o -framework GSS -Wno-error=unused-command-line-argument-hard-error-in-future
  clang: warning: -framework GSS: 'linker' input unused [-Wunused-command-line-argument]
  warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
  gssapi/bindings/__pycache__/_cffi__xa89f429exac4dd3e8.c:480:57: warning: passing 'const gss_name_t *' (aka 'struct gss_name_t_desc_struct *const *') to parameter of type 'gss_name_t  _Nullable * _Nullable' (aka 'struct gss_name_t_desc_struct **') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    { result = gss_accept_sec_context(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10); }
                                                          ^~
  /System/Library/Frameworks/GSS.framework/Headers/gssapi_protos.h:67:37: note: passing argument to parameter 'src_name' here
          __nullable gss_name_t * __nullable src_name,
                                             ^
  gssapi/bindings/__pycache__/_cffi__xa89f429exac4dd3e8.c:4397:3: warning: code will never be executed [-Wunreachable-code]
    _cffi_check_struct_gss_OID_desc_struct(0);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  gssapi/bindings/__pycache__/_cffi__xa89f429exac4dd3e8.c:4424:3: warning: code will never be executed [-Wunreachable-code]
    _cffi_check_struct_gss_OID_set_desc_struct(0);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  gssapi/bindings/__pycache__/_cffi__xa89f429exac4dd3e8.c:4451:3: warning: code will never be executed [-Wunreachable-code]
    _cffi_check_struct_gss_buffer_desc_struct(0);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  gssapi/bindings/__pycache__/_cffi__xa89f429exac4dd3e8.c:4487:3: warning: code will never be executed [-Wunreachable-code]
    _cffi_check_struct_gss_channel_bindings_struct(0);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  6 warnings generated.
  clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/Users/tommy/.pyenv/versions/3.7.2/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/Users/tommy/.pyenv/versions/3.7.2/lib build/temp.macosx-10.14-x86_64-3.7/gssapi/bindings/__pycache__/_cffi__xa89f429exac4dd3e8.o -o build/lib.macosx-10.14-x86_64-3.7/gssapi/bindings/_cffi__xa89f429exac4dd3e8.cpython-37m-darwin.so -framework GSS
  installing to build/bdist.macosx-10.14-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.14-x86_64
  creating build/bdist.macosx-10.14-x86_64/wheel
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi_ez_setup.py -> build/bdist.macosx-10.14-x86_64/wheel
  creating build/bdist.macosx-10.14-x86_64/wheel/gssapi
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/error.py -> build/bdist.macosx-10.14-x86_64/wheel/gssapi
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/creds.py -> build/bdist.macosx-10.14-x86_64/wheel/gssapi
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/chanbind.py -> build/bdist.macosx-10.14-x86_64/wheel/gssapi
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/__init__.py -> build/bdist.macosx-10.14-x86_64/wheel/gssapi
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/names.py -> build/bdist.macosx-10.14-x86_64/wheel/gssapi
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/oids.py -> build/bdist.macosx-10.14-x86_64/wheel/gssapi
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/__about__.py -> build/bdist.macosx-10.14-x86_64/wheel/gssapi
  creating build/bdist.macosx-10.14-x86_64/wheel/gssapi/bindings
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/bindings/autogenerated.cdef -> build/bdist.macosx-10.14-x86_64/wheel/gssapi/bindings
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/bindings/__init__.py -> build/bdist.macosx-10.14-x86_64/wheel/gssapi/bindings
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/bindings/cffi_gssapi.cdef -> build/bdist.macosx-10.14-x86_64/wheel/gssapi/bindings
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/bindings/_cffi__xa89f429exac4dd3e8.cpython-37m-darwin.so -> build/bdist.macosx-10.14-x86_64/wheel/gssapi/bindings
  copying build/lib.macosx-10.14-x86_64-3.7/gssapi/ctx.py -> build/bdist.macosx-10.14-x86_64/wheel/gssapi
  running install_egg_info
  running egg_info
  writing python_gssapi.egg-info/PKG-INFO
  writing dependency_links to python_gssapi.egg-info/dependency_links.txt
  writing requirements to python_gssapi.egg-info/requires.txt
  writing top-level names to python_gssapi.egg-info/top_level.txt
  reading manifest file 'python_gssapi.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'python_gssapi.egg-info/SOURCES.txt'
  Copying python_gssapi.egg-info to build/bdist.macosx-10.14-x86_64/wheel/python_gssapi-0.6.4-py3.7.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/7s/9r15tdh50rz2n2ndx43j2m3w0000gp/T/pip-install-3zpmrshy/python-gssapi/setup.py", line 74, in <module>
      url="https://github.com/sigmaris/python-gssapi",
    File "/Users/tommy/.pyenv/versions/3.7.2/envs/paramiko/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Users/tommy/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/tommy/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/tommy/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/tommy/.pyenv/versions/3.7.2/envs/paramiko/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/Users/tommy/.pyenv/versions/3.7.2/envs/paramiko/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/tommy/.pyenv/versions/3.7.2/envs/paramiko/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError

  ----------------------------------------
  Failed building wheel for python-gssapi
  Running setup.py clean for python-gssapi
Failed to build python-gssapi
Installing collected packages: python-gssapi
  Running setup.py install for python-gssapi ... done
Successfully installed python-gssapi-0.6.4
```

**Comment by frozencemetery** [comment]
@sigmaris any ideas here?

**Comment by sigmaris** [comment]
@tommyjcarpenter Just FYI, the package you're installing is the older https://github.com/sigmaris/python-gssapi/ and not this package, unfortunately Paramiko still requires the older package until https://github.com/paramiko/paramiko/pull/1311 is merged.

Anyway, having said that, it looks like this may not be a problem with the python-gssapi package; the error is coming from the internals of the wheel package. 

What seems to happen in your install log is that pip tries to build a wheel to install, fails and then falls back to installing straight from source. But notice the final line is still:

```
Successfully installed python-gssapi-0.6.4
```
So it did install successfully from source in the end, and you should be able to use the package.

If for some reason you want to build a wheel, try upgrading the "wheel" package in the Python environment you're using to the latest version, 0.33.1 which might help. I did a quick test and it seemed to work on Python 3.7.2 on Mac OS 10.13.6 which is the only version I have handy right now.

**Comment by tommyjcarpenter** [comment]
Thank you for the guidance.
