### ISSUE TITLE
how to build with pyinstaller

### ISSUE THREAD

**Issue by pythonwood** [pythongssapi/python-gssapi#224]
Ubuntu 18 + Python3.6 + PyInstaller 4 + pyfilesystem2

I am writing a devops tool using python and build with pyinstaller.

### What went wrong?

pyinstaller to build bin file ok but run failed.

**fs.sshfs -> paramiko/ssh_gss.py -> gssapi/__init__.py ->gssapi/bindings/__init__.py**

```

./a.bin
.......

  File "fs/sshfs/sshfs.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "pyvenv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paramiko/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "pyvenv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paramiko/transport.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "pyvenv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paramiko/auth_handler.py", line 72, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "pyvenv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "paramiko/ssh_gss.py", line 49, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "pyvenv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "gssapi/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "pyvenv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "gssapi/bindings/__init__.py", line 230, in <module>
  File "gssapi/bindings/__init__.py", line 187, in _read_header
  File "pkg_resources/__init__.py", line 1133, in resource_exists
  File "pkg_resources/__init__.py", line 1404, in has_resource
  File "pkg_resources/__init__.py", line 1474, in _has
NotImplementedError: Can't perform this operation for unregistered loader type
[13996] Failed to execute script run

```

after uninstalling python-gssapi and build again, run it pass !

**Comment by pythonwood** [comment]
```
pip uninstall python-gssapi # python-gssapi is old !
pip install gssapi

```
then minize a project to test

$ cat pyi_gssapi.py

```
from pprint import pprint
import gssapi

print("__file__", __file__)
print("__name__", __name__)
print("__package__", __package__)
print('gssapi.__path__', gssapi.__path__)

pprint(vars(gssapi))

```

build:


```
pyinstaller --distpath .  pyi_gssapi.py
cd ./pyi_gssapi
./pyi_gssapi

Traceback (most recent call last):
  File "pyi_gssapi.py", line 2, in <module>
  File "/tmp/env/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "gssapi/__init__.py", line 31, in <module>
  File "/tmp/env/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "gssapi/raw/__init__.py", line 50, in <module>
  File "gssapi/raw/creds.pyx", line 1, in init gssapi.raw.creds
  File "gssapi/raw/names.pyx", line 6, in init gssapi.raw.names
  File "gssapi/raw/misc.pyx", line 1, in init gssapi.raw.misc
ModuleNotFoundError: No module named 'gssapi.raw.cython_converters'
[23139] Failed to execute script pyi_gssapi

```

**Comment by frozencemetery** [comment]
Hi, thank you for your interest in this project.  However, I have never worked with pyinstaller before.

It looks from your traceback like pyinstaller doesn't support cython, or didn't run our build correctly.

If there's a change to be made on the python-gssapi side to support this use case, I'm happy to consider it.  But I can't investigate this issue myself.  I suggest you check with the pyinstaller folks for next steps.
