### ISSUE TITLE
MacOS Python3.8 raise NotImplementedError

### ISSUE THREAD

**Issue by deadwind4** [pythongssapi/python-gssapi#240]
### What went wrong?
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    with krbcontext(using_keytab=True, keytab_file='foo.keytab', principal='foo@FOO.COM') as krb:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/krbcontext/context.py", line 275, in __enter__
    self._prepare_context()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/krbcontext/context.py", line 265, in _prepare_context
    self.init_with_keytab()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/krbcontext/context.py", line 156, in init_with_keytab
    creds = gssapi.creds.Credentials(**creds_opts)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gssapi/creds.py", line 63, in __new__
    res = cls.acquire(name, lifetime, mechs, usage,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gssapi/creds.py", line 140, in acquire
    raise NotImplementedError("Your GSSAPI implementation does "
NotImplementedError: Your GSSAPI implementation does not have support for manipulating credential stores

### How do we reproduce?

from hdfs.ext.kerberos import KerberosClient
from krbcontext import krbcontext
import os

hdfs_url = 'http://foo:50070'
with krbcontext(using_keytab=True, keytab_file='foo.keytab', principal='foo@FOO.COM') as krb:
    client = KerberosClient(hdfs_url)
    client._list_status('/').json()['FileStatuses']['FileStatus']

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)
python version：3.8.3
python-gssapi version: 1.6.12
OS：Mac OS Big Sur 11.1

**Comment by jborean93** [comment]
The GSSAPI implementation on macOS does not offer the extensions required to manage credential stores, there's nothing python-gssapi can do about that. You will have to install a custom MIT or Heimdal GSSAPI version and compile python-gssapi against that but this is no easy task.

**Comment by frozencemetery** [comment]
(Closing per @jborean93's comment above.)
