### ISSUE TITLE
misc.c missing

### ISSUE THREAD

**Issue by nmz787** [pythongssapi/python-gssapi#275]
using head of repo as of now...
* python3.7.4 setup.py install --user

```
Cython not found, building from C files...
Traceback (most recent call last):
  File "setup.py", line 376, in <module>
    main_file('misc'),
  File "setup.py", line 297, in main_file
    return make_extension('gssapi.raw.%s', module)
  File "setup.py", line 283, in make_extension
    raise OSError(source)
OSError: gssapi/raw/misc.c```

**Comment by jborean93** [comment]
I've just checked the latest release on PyPI and the sdist on there definitely contains the C files, including `misc.c`

![image](https://user-images.githubusercontent.com/8462645/137061520-7bf66874-7421-4be6-a548-a2dc2fa3bfec.png)

If you are installing from a git checkout then yes you will need `Cython` to generate the C files and the error you receive is expected if `Cython` is not installed.

The error you've commented in https://github.com/pythongssapi/python-gssapi/issues/131#issuecomment-941872366 is an indication your header files don't contain the references required to build `python-gssapi`. Can you share some more information on your host setup like what OS, what versions, what GSSAPI provider have you installed and how, + anything else you might think is relevant.
