### ISSUE TITLE
Segfault in display_as with mech type kerberos

### ISSUE THREAD

**Issue by msimacek** [pythongssapi/python-gssapi#77]
Reproducer:
python -c 'import gssapi as g;n=g.Name("x");n.display_as(g.MechType.kerberos)'

Stack:
#0  0x00007fffef2da46f in gss_display_name_ext () from /lib64/libgssapi_krb5.so.2
#1  0x00007fffeb29416d in __pyx_pw_6gssapi_3raw_11ext_rfc6680_1display_name_ext ()
   from /usr/lib64/python2.7/site-packages/gssapi/raw/ext_rfc6680.so
#2  0x00007ffff7af28be in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#3  0x00007ffff7af2666 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#4  0x00007ffff7af36b4 in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#5  0x00007ffff7af37d9 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#6  0x00007ffff7b0cbdf in run_mod () from /lib64/libpython2.7.so.1.0
#7  0x00007ffff7b0da54 in PyRun_StringFlags () from /lib64/libpython2.7.so.1.0
#8  0x00007ffff7b0f36b in PyRun_SimpleStringFlags () from /lib64/libpython2.7.so.1.0
#9  0x00007ffff7b20b80 in Py_Main () from /lib64/libpython2.7.so.1.0
#10 0x00007ffff6d3f630 in __libc_start_main () from /lib64/libc.so.6
#11 0x0000555555554839 in _start ()

Version info:
Running freshly installed Fedora Rawhide.
python-gssapi-1.1.2-1.fc24.x86_64
krb5-libs-1.13.2-6.fc23.x86_64

**Comment by msimacek** [comment]
Looking at the source, I'm passing object of incorrect type, it requires NameType not MechType
