### ISSUE TITLE
TypeError in display_as with mech type mro

### ISSUE THREAD

**Issue by msimacek** [pythongssapi/python-gssapi#78]
Reproducer:
python -c 'import gssapi as g;n=g.Name("x");n.display_as(g.MechType.mro)'

Stacktrace:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/gssapi/names.py", line 145, in display_as
    return rname_rfc6680.display_name_ext(self, name_type).encode(
TypeError: Argument 'name_type' has incorrect type (expected gssapi.raw.oids.OID, got builtin_function_or_method)

Running Fedora Rawhide with python-gssapi-1.1.2-1.fc24.x86_64

#77 seems related

**Comment by msimacek** [comment]
Passing incorrect type, sorry for the noise
