### ISSUE TITLE
Create release with python 3.5 support

### ISSUE THREAD

**Issue by pefoley2** [pythongssapi/python-gssapi#87]
The enum34 requirement fails to build properly when running `pip install gssapi` under python 3.5.
As the enum34 package is unnecessary for python3.5, would it be possible to publish a new release containing the fix in d4b5c71?

Collecting enum34 (from gssapi==1.1.3->-r requirements.txt (line 14))
  Downloading enum34-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-sfiuv82x/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extension import Extension
      File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/setuptools/extension.py", line 8, in <module>
        from .dist import _get_unpatched
      File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/setuptools/dist.py", line 16, in <module>
        from setuptools.depends import Require
      File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/setuptools/depends.py", line 6, in <module>
        from setuptools import compat
      File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/setuptools/compat.py", line 45, in <module>
        import http.client as httplib
      File "/opt/python/3.5.0/lib/python3.5/http/client.py", line 71, in <module>
        import email.parser
      File "/opt/python/3.5.0/lib/python3.5/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser, BytesFeedParser
      File "/opt/python/3.5.0/lib/python3.5/email/feedparser.py", line 27, in <module>
        from email import message
      File "/opt/python/3.5.0/lib/python3.5/email/message.py", line 16, in <module>
        from email import utils
      File "/opt/python/3.5.0/lib/python3.5/email/utils.py", line 29, in <module>
        import socket
      File "/opt/python/3.5.0/lib/python3.5/socket.py", line 73, in <module>
        IntEnum._convert(
      File "/tmp/pip-build-sfiuv82x/enum34/enum/__init__.py", line 373, in __getattr__
        raise AttributeError(name)
    AttributeError: _convert

**Comment by frozencemetery** [comment]
Yes, I'll look into publishing a 1.1.4 with d4b5c712a0739e1e1229472781fbe7bf0dd43749 in it.
