### ISSUE TITLE
MAC OSX 10.10.5 AttributeError: 'module' object has no attribute 'Name'

### ISSUE THREAD

**Issue by robgil** [pythongssapi/python-gssapi#91]
The demo is failing on the constant gssapi.C_NT_HOSTBASED_SERVICE in CentOS 6.
* Python 2.7.9
* OSX 10.10.5

```python
import gssapi

# Create a Name identifying the target service
service_name = gssapi.Name('HTTP@<myserver>', gssapi.C_NT_HOSTBASED_SERVICE)
# Create an InitContext targeting the demo service
ctx = gssapi.InitContext(service_name)

# Loop sending tokens to, and receiving tokens from, the server
# until the context is established
in_token = None
while not ctx.established:
    out_token = ctx.step(in_token)
    if out_token:
        send_to_server(out_token)
    if ctx.established:
        break
    in_token = receive_from_server()
    if not in_token:
        raise Exception("No response from server.")

print("Successfully authenticated.")

```
Output
```
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
    import gssapi
  File "/Users/rgil/kerb/gssapi.py", line 4, in <module>
AttributeError: 'module' object has no attribute 'Name'
```

**Comment by DirectXMan12** [comment]
This demo looks like it did not come from our documentation.  Our documentation is at https://pythonhosted.org/gssapi ?  It looks like it's from the @sigmaris's old python-gssapi library, which should be marked as deprecated.
